{% set name = "napari-ndtiffs" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4e290f2d87e4a9a1020ff5b8ad66f4a6d92f5ea6daadd60b937beae4b5312054

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - dask-core
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - python-dateutil
    - scipy
    - tifffile
    - pyopencl

test:
  imports:
    - napari_ndtiffs
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - platformdirs   # fix false positive with pip check

about:
  home: https://github.com/tlambert03/napari-ndtiffs
  summary: napari plugin for nd tiff folders with OpenCl deskew
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tlambert03
